export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    CHECKOUT_ORDER: 'CHECKOUT_ORDER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SAVE_URL: 'SAVE_URL'
}